/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leon_app3_MainActivity */

#ifndef _Included_com_leon_app3_MainActivity
#define _Included_com_leon_app3_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leon_app3_MainActivity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leon_app3_MainActivity_hello
  (JNIEnv *, jobject);

/*
 * Class:     com_leon_app3_MainActivity
 * Method:    hello1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leon_app3_MainActivity_hello1
  (JNIEnv *, jobject);

/*
 * Class:     com_leon_app3_MainActivity
 * Method:    hello2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leon_app3_MainActivity_hello2
  (JNIEnv *, jobject);

/*
 * Class:     com_leon_app3_MainActivity
 * Method:    hello3
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leon_app3_MainActivity_hello3
  (JNIEnv *, jobject);

/*
 * Class:     com_leon_app3_MainActivity
 * Method:    hello4
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leon_app3_MainActivity_hello4
  (JNIEnv *, jobject);

/*
 * Class:     com_leon_app3_MainActivity
 * Method:    hello5
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leon_app3_MainActivity_hello5
  (JNIEnv *, jobject);

/*
 * Class:     com_leon_app3_MainActivity
 * Method:    hello6
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leon_app3_MainActivity_hello6
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
